USE pijava;

CREATE TABLE CLIENT_REGISTER(
CLIENT_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
CLIENT_CPF VARCHAR(11) NOT NULL,
CLIENT_NAME VARCHAR(40) NOT NULL,
CLIENT_ZIP_COD VARCHAR(8) NOT NULL,
CLIENT_STREET_NAME VARCHAR(40) NOT NULL,
CLIENT_STREET_NUMBER INTEGER(10) NOT NULL,
CLIENT_STREET_COMPLEMENT VARCHAR(40),
CLIENT_CITY VARCHAR (40) NOT NULL,
CLIENT_STATE VARCHAR(2) NOT NULL,
CLIENT_METER_NUMBER VARCHAR(10) NOT NULL,
CLIENT_MEASUREMENT_ORDER VARCHAR(10) NOT NULL,
CLIENT_LIGHT_CLASS VARCHAR(20) NOT NULL,
CLIENT_LIGHT_SUBCLASS VARCHAR(40) NOT NULL,
CLIENT_NORMAL_TAX NUMERIC(15,5) NOT NULL,
CLIENT_TRIBUTE_TAX NUMERIC(15,5),
CLIENT_SUPPLIER_CNPJ VARCHAR(14),
CONSTRAINT FK_CLIENTSUPPLIER FOREIGN KEY (CLIENT_SUPPLIER_CNPJ) REFERENCES SUPPLIER (SUPPLIER_CNPJ)
);

ALTER TABLE CLIENT_REGISTER MODIFY COLUMN CLIENT_STREET_NAME VARCHAR(40);