USE PIJava;

CREATE TABLE LIGHT_ACCOUNT(

	ACCOUNT_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_IDENT_COD INTEGER(10) NOT NULL,
    ACCOUNT_METER_NUMBER VARCHAR(10) NOT NULL,
    ACCOUNT_INVOICE VARCHAR(10) NOT NULL,
    ACCOUNT_CURRENT_DATE VARCHAR(13) NOT NULL,
    ACCOUNT_DUE_DATE VARCHAR(13) NOT NULL,
    ACCOUNT_CONSUMPTION_DAYS INTEGER(3) NOT NULL,
    ACCOUNT_FLAG_TYPE VARCHAR(10) NOT NULL,
    ACCOUNT_CONSUMPTION_VALUE NUMERIC(15,2) NOT NULL,
    ACCOUNT_PIS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    ACCOUNT_COFINS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    ACCOUNT_ICMS_BASIS NUMERIC(15,2) NOT NULL,
    ACCOUNT_ICMS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    ACCOUNT_ICMS_VALUE NUMERIC(15,2) NOT NULL,
    ACCOUNT_PIS_COFINS_BASIS NUMERIC(15,2) NOT NULL,
    ACCOUNT_PIS_VALUE NUMERIC(15,2) NOT NULL,
    ACCOUNT_COFINS_VALUE NUMERIC(15,2) NOT NULL,
    ACCOUNT_FORFEIT_VALUE NUMERIC(15,2),
    ACCOUNT_INTEREST_VALUE NUMERIC(15,2),
    ACCOUNT_OTHER_VALUES NUMERIC(15,2),
    ACCOUNT_SUPPLY_VALUES NUMERIC(15,2),
    ACCOUNT_FINANCIAL_ITEMS NUMERIC(15,2),
    ACCOUNT_AMOUNT NUMERIC(15,2) NOT NULL,
    ACCOUNT_SUPPLIER_CNPJ VARCHAR(14),
    CONSTRAINT FK_LIGHTSUPPLIERS FOREIGN KEY (ACCOUNT_SUPPLIER_CNPJ) REFERENCES SUPPLIER (SUPPLIER_CNPJ)
   
    
);
